name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - run: next build
        env:
          MAPKIT_KEY: ${{ secrets.MAPKIT_KEY }}
          KID: ${{ secrets.KID }}
          ISS: ${{ secrets.ISS }}
          BYTEBIN_AUTH_KEY: ${{ secrets.BYTEBIN_AUTH_KEY }}
      - run: next export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          #cname: showplaces.ocelotwrangler.com
